# Generated by Django 5.0.6 on 2024-09-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_voted',
            field=models.BooleanField(default=False),
        ),
    ]
