# Generated by Django 5.0.6 on 2025-01-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_has_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_voted',
        ),
    ]
