# Generated by Django 5.0.6 on 2024-09-12 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['username'], name='spotify_vot_usernam_db3013_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['song_id'], name='spotify_vot_song_id_f836c7_idx'),
        ),
    ]
