# Generated by Django 5.0.6 on 2025-01-20 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote_spotify_vot_usernam_db3013_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_vote',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='spotify_vot_song_id_f836c7_idx',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='song_id',
            new_name='song',
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['song'], name='spotify_vot_song_id_d913d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('username', 'song'), name='unique_vote'),
        ),
    ]
